apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels: 
    name: my-first-pod
    app: demo-app
spec:
  containers:
    - name: my-first-container
      image: nginx
      ports:
        - containerPort: 80
