apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  labels:
    name: my-first-service
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: my-first-pod
    app: demo-app
